### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by lelelofy** [sAjibuu/upload_bypass_carnage#1]
ERROR: Ignored the following versions that require a different python version: 0.0.12 Requires-Python >=3.5, <3.8
ERROR: Could not find a version that satisfies the requirement pickle5==0.0.12 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.0.10, 0.0.11)
ERROR: No matching distribution found for pickle5==0.0.12

**Comment by sAjibuu** [comment]
You are more than welcome to download the new version of the tool, which no longer requires the pickle library.
